Added .env
fzerorubigd/engine pull request #2
Opened 2019-12-28 14:00 UTC by ErFUN-KH

Now it's easier to use

2020-01-04 09:24 UTC, fzerorubigd commented
I am not sure if I want to add .env (with a requirement for an external tool to load the env) to the project.

2020-01-23 12:34 UTC, ErFUN-KH commented
Sorry, I forget to include .env, I think it will work without any external tools now.
if it doesn't work for you, please tell me whats your os, I'll fix it.

2020-05-22 19:14 UTC, fzerorubigd requested changes
This breaks the circleci test, since those scripts are using the make file and the make. 

Another issue is the `.env`, it is a defacto name for all env loaders (like direnv) and also docker-compose , (which I have plan to migrate the development from vagrant to it)

2020-05-22 19:14 UTC, fzerorubigd commented on Makefile
>  export DOKKU_HOST=elbix.dev
Move this one into .env

2024-03-28 18:42 UTC, closed without merging